// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBFDZigInTT8_WzQcovkjFoPPHLr3Qe6k',
    appId: '1:689136306740:web:5c6052e8b8f29f7f8cd861',
    messagingSenderId: '689136306740',
    projectId: 'quizapp-30692',
    authDomain: 'quizapp-30692.firebaseapp.com',
    storageBucket: 'quizapp-30692.firebasestorage.app',
    measurementId: 'G-GM5GQ4Z7J4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBogi3qTTZtzBk3aflIUp2L5v3FtpqT5QU',
    appId: '1:689136306740:android:100d46e53e6cd8e58cd861',
    messagingSenderId: '689136306740',
    projectId: 'quizapp-30692',
    storageBucket: 'quizapp-30692.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjKoY_cEB0UYoA7NiE_DAq--TtdJsVVmg',
    appId: '1:689136306740:ios:c05892caf413b5fc8cd861',
    messagingSenderId: '689136306740',
    projectId: 'quizapp-30692',
    storageBucket: 'quizapp-30692.firebasestorage.app',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjKoY_cEB0UYoA7NiE_DAq--TtdJsVVmg',
    appId: '1:689136306740:ios:c05892caf413b5fc8cd861',
    messagingSenderId: '689136306740',
    projectId: 'quizapp-30692',
    storageBucket: 'quizapp-30692.firebasestorage.app',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBFDZigInTT8_WzQcovkjFoPPHLr3Qe6k',
    appId: '1:689136306740:web:85b300aba021e1878cd861',
    messagingSenderId: '689136306740',
    projectId: 'quizapp-30692',
    authDomain: 'quizapp-30692.firebaseapp.com',
    storageBucket: 'quizapp-30692.firebasestorage.app',
    measurementId: 'G-X6ZJH97T7X',
  );
}
